[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "i2c-helper"
version = "0.1.1"
requires-python = ">=3.9"
dependencies = [
    "diag-test-common",
    "keygen",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.sources]
keygen = { path = "../../Local Libraries/keygen-1.2.0-py3-none-any.whl" }
diag-test-common = { path = "../../Local Libraries/diag_test_common-0.0.9-py3-none-any.whl" }
